# Generated by Django 5.0.9 on 2024-10-28 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporation",
            name="founding_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="corporation",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
